### ISSUE TITLE
"On overdrive" reports on wrong book

### ISSUE THREAD

**Issue by whozits** [rhollister/goodreads#6] opened 2015-11-28 20:25 UTC
I added Bernard Cornwell's "Waterloo: The True Story of Four Days, Three Armies and Three Battles" to my to-read list but extension reports on his "Sharpe's Waterloo" instead.  

I don't know if this should be reported as a separate issue, but my Avast anti-virus reports your extension as malware.

**Comment by rhollister** [comment] 2015-11-28 22:48
Good question! The reason is the extension uses two strategies to try find the book:

1. Instead of searching by ISBN for that specific edition or print, it searches Overdrive by b

**Comment by rhollister** [comment] 2015-11-28 23:05
Good question, thanks for reporting this! The reason for this is the extension uses two strategies to try find the book on Overdrive:
1. Instead of searching by ISBN for that specific edition or print, it simply searches Overdrive for "book title and author".
2. It also strips out everything in the title after a colon in case Overdrive doesn't list the subtitles.

The effect of this is that in this case this author wrote other books on Waterloo so those are showing up as well. I originally added the hover-over display to help resolve this exact scenario.

What's your opinion on this behavior?
1. Is the current behavior reasonable, or pretty obnoxious? 
2. Would you prefer to do an exact search with the subtitle and not have your to-read list cluttered with results?
3. What about an option to turn "fuzzy searching" on/off?

Thanks for the head's up about Avast, I'll send them an email and see what the problem is. It might be because the extension wants permission to contact api.statdns.com (it does so as a last-ditch effort to look up a library's Overdrive URL).

**Comment by rhollister** [comment] 2015-11-28 23:41
Actually. due to a bug, you can juxtapose both types of search behavior right now. Currently the extension strips out the subtitles in your bookshelf listing, but not in the book description page.

Compare the listing for this book in your to-reads list and in the book page: https://www.goodreads.com/book/show/22007249-waterloo

Without stripping out the subtitle, it appears as "not found" in Overdrive, but stripping out the subtitle does find the book (along with a few other books by the author). 

I fixed the inconsistent behavior so it should be fixed in a few days from now. I think this is a good example of why it should strip out subtitles even though it means a few extra listings. What do you think?

**Comment by whozits** [comment] 2015-11-29 01:11
I think the extension should report a title as "not found" if the title
really isn't found.  As the saying goes, "close only counts in horseshoes
and hand grenades."

But I do like that the extension trims off the subtitle when hovering over
the link.

Keep up the good work
Alan

**Closed as completed** 2017-03-23 00:11 UTC
